# Generated by Django 4.2.11 on 2026-04-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ics_url', models.URLField()),
                ('source', models.CharField(choices=[('TEAM_CENTRAL', 'Team Central'), ('ADMIN', 'Admin Schedule')], default='TEAM_CENTRAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='league.team')),
            ],
            options={
                'unique_together': {('team', 'ics_url')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('opponent', models.CharField(blank=True, help_text="Parsed opponent (e.g., 'Tigers')", max_length=255)),
                ('event_type', models.CharField(choices=[('GAME', 'Game'), ('PRACTICE', 'Practice'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('TEAM_CENTRAL', 'Team Central'), ('ADMIN', 'Admin')], max_length=20)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='league.teamcalendar')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='league.team')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('external_id', 'source'), name='unique_event_per_source'),
        ),
    ]
