# Generated by Django 4.2.11 on 2026-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_teamcalendar_event_event_unique_event_per_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcalendar',
            old_name='last_sync_at',
            new_name='last_synced_at',
        ),
        migrations.AlterUniqueTogether(
            name='teamcalendar',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teamcalendar',
            name='ics_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='teamcalendar',
            index=models.Index(fields=['team', 'is_active'], name='league_team_team_id_8bae1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamcalendar',
            constraint=models.UniqueConstraint(fields=('team', 'ics_url'), name='unique_team_calendar_url'),
        ),
    ]
