# Generated by Django 4.2.11 on 2026-04-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_rename_last_sync_at_teamcalendar_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='field',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
