# Generated by Django 4.2.11 on 2026-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_event_field_event_field_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
