# Generated by Django 4.2.11 on 2026-05-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_draft_draftselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_hand',
            field=models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('switch', 'Switch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='throwing_hand',
            field=models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('switch', 'Switch')], max_length=10),
        ),
    ]
