# Generated by Django 4.2.11 on 2026-06-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_player_batting_hand_alter_player_throwing_hand'),
        ('league', '0015_evaluation_signup'),
    ]

    operations = [
    ]
