# Generated by Django 4.2.11 on 2026-06-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_merge_20260602_1008'),
        ('league', '0017_budget_categories_fy26_data'),
    ]

    operations = [
    ]
