# Generated by Django 4.2.11 on 2026-06-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_merge_20260603_1600'),
        ('league', '0018_uploaded_document'),
    ]

    operations = [
    ]
