# Generated by Django 4.2.11 on 2026-06-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_team_home_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationsignupwindow',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Mark this window as active/current season.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: hides the player from active views. Only deletable from the recycling bin.'),
        ),
        migrations.AlterField(
            model_name='playerprogramenrollment',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='league.division'),
        ),
        migrations.AlterField(
            model_name='playerprogramenrollment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.team'),
        ),
    ]
