# Generated by Django 4.2.11 on 2026-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_program_year_player_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['season_year', 'program_type']},
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active in the current season. Set to False when a new program year starts; restored on import.'),
        ),
    ]
