# Generated by Django 4.2.11 on 2026-06-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_alter_program_options_alter_player_is_active'),
        ('league', '0024_phone_fields'),
    ]

    operations = [
    ]
