# Generated by Django 4.2.11 on 2026-06-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_evaluationevent_divisions'),
        ('league', '0026_merge_0025_evaluation_event_0025_merge_20260604_1340'),
    ]

    operations = [
    ]
