# Generated by Django 4.2.11 on 2026-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_merge_20260604_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluationevent',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When True, the public sign-up form is enabled.'),
        ),
        migrations.AlterField(
            model_name='evaluationevent',
            name='name',
            field=models.CharField(help_text="e.g. '2026 Spring Baseball Evaluations'", max_length=200),
        ),
        migrations.AlterField(
            model_name='evaluationevent',
            name='slots_per_hour',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 slot/hr (every 60 min)'), (2, '2 slots/hr (every 30 min)'), (3, '3 slots/hr (every 20 min)'), (4, '4 slots/hr (every 15 min)'), (6, '6 slots/hr (every 10 min)')], default=4, help_text='How many player slots per hour'),
        ),
        migrations.AlterField(
            model_name='evaluationevent',
            name='start_time',
            field=models.TimeField(help_text='Time the first slot begins'),
        ),
        migrations.AlterField(
            model_name='evaluationevent',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=3, help_text='Total evaluation window in hours (e.g. 3.5)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluationregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluationregistration',
            name='specialty_position',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pitcher', 'Pitcher'), ('catcher', 'Catcher')], default='', help_text='Pitcher or Catcher — only applicable for AAA/Majors', max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluationtimeslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
