# Generated by Django 4.2.11 on 2026-06-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_division_calendar_only_team_calendar_crud'),
        ('league', '0028_alter_evaluationevent_id_and_more'),
    ]

    operations = [
    ]
