# Generated by Django 4.2.11 on 2026-06-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0034_allstar_uniforms_patches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='is_calendar_only',
            field=models.BooleanField(default=False, help_text='If True, this division appears only in calendar/schedule views and is excluded from player lists, evaluations, All Stars, etc.'),
        ),
    ]
