# Generated by Django 4.2.11 on 2026-06-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0035_alter_division_is_calendar_only'),
        ('league', '0035_board_member'),
    ]

    operations = [
    ]
