# Generated by Django 4.2.11 on 2026-06-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0036_merge_20260605_2024'),
        ('league', '0037_event_concessions_closed'),
    ]

    operations = [
    ]
