# Generated by Django 4.2.11 on 2026-06-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0039_districtleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Player Agent', 'Player Agent'), ('Safety Officer', 'Safety Officer'), ('Fundraising', 'Fundraising'), ('Sponsorship', 'Sponsorship'), ('Concessions', 'Concessions'), ('Grounds', 'Grounds'), ('Equipment Manager', 'Equipment Manager'), ('Umpire Coordinator', 'Umpire Coordinator'), ('Marketing', 'Marketing'), ('Information Officer', 'Information Officer'), ('At-Large', 'At-Large'), ('Other', 'Other')], default='At-Large', max_length=100),
        ),
    ]
