# Generated by Django 4.2.11 on 2026-06-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0040_alter_boardmember_role'),
        ('league', '0040_boardmember_sport'),
    ]

    operations = [
    ]
