# Generated by Django 4.2.11 on 2026-06-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0041_merge_20260608_1658'),
        ('league', '0041_vendor'),
    ]

    operations = [
    ]
