# Generated by Django 4.2.11 on 2026-06-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0047_event_external_id_drop_unique'),
        ('league', '0050_leaguelocation_league_fk'),
    ]

    operations = [
    ]
