# Generated by Django 4.2.11 on 2026-06-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0051_merge_20260623_1358'),
        ('league', '0052_user_umpire_board_member'),
    ]

    operations = [
    ]
