# Generated by Django 4.2.11 on 2026-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0055_fundraising_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueidentity',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public contact email address. Used in magic link emails.', max_length=254),
        ),
        migrations.AlterField(
            model_name='leagueidentity',
            name='league_name',
            field=models.CharField(default='Washington Township Little League', help_text='Full official league name.', max_length=150),
        ),
        migrations.AlterField(
            model_name='leagueidentity',
            name='primary_color',
            field=models.CharField(default='#C41230', help_text='Primary brand color as a hex code (e.g. #C41230).', max_length=7),
        ),
        migrations.AlterField(
            model_name='leagueidentity',
            name='secondary_color',
            field=models.CharField(default='#1565c0', help_text='Secondary brand color as a hex code.', max_length=7),
        ),
        migrations.AlterField(
            model_name='leagueidentity',
            name='short_name',
            field=models.CharField(default='WTLL', help_text='Abbreviation shown in nav and tight spaces.', max_length=20),
        ),
        migrations.AlterField(
            model_name='leagueidentity',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Optional short tagline shown on public pages.', max_length=200),
        ),
        migrations.AlterField(
            model_name='leagueidentity',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text='League website URL.'),
        ),
    ]
