# Generated by Django 4.2.11 on 2026-06-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0056_alter_leagueidentity_contact_email_and_more'),
        ('league', '0060_campaign_type_inkind'),
    ]

    operations = [
    ]
