# Generated by Django 4.2.11 on 2026-06-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0064_boardcalendarevent_boardchecklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcalendarevent',
            name='phase',
            field=models.CharField(blank=True, help_text='Month phase label, e.g. "Fall Ball Launch"', max_length=150),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='division',
            field=models.CharField(blank=True, choices=[('TEE_BALL', 'Tee Ball'), ('PEE_WEE', 'Pee Wee'), ('AAA', 'AAA'), ('MAJORS', 'Majors'), ('SF_MINORS', 'Softball Minors'), ('SF_MAJORS', 'Softball Majors'), ('ALL_DIV', 'All Divisions')], help_text='Baseball/Softball division this item applies to. Leave blank for cross-division items.', max_length=20),
        ),
    ]
