# Generated by Django 4.2.11 on 2026-06-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0065_alter_boardcalendarevent_phase_and_more'),
        ('league', '0068_sitesettings_modules'),
    ]

    operations = [
    ]
