# Generated by Django 4.2.11 on 2026-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0069_merge_20260626_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='module_involvement_enabled',
            field=models.BooleanField(default=True, help_text='Enable Involvement section (Umpire, Volunteer, and Evaluation sign-ups).'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='account_name',
            field=models.CharField(blank=True, help_text="Name the account is registered under, if different from the league's current name.", max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='products',
            field=models.TextField(blank=True, help_text="Comma-separated list of products/services this vendor supplies. E.g. 'Field chalk, Field paint, Mound clay'"),
        ),
        migrations.AlterField(
            model_name='vendorlocation',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary/preferred location'),
        ),
        migrations.AlterField(
            model_name='vendorlocation',
            name='label',
            field=models.CharField(help_text='Short label, e.g. "Fishers (Primary)" or "Indianapolis"', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorlocation',
            name='notes',
            field=models.TextField(blank=True, help_text='Location-specific notes, e.g. delivery area, pickup only'),
        ),
    ]
