# Generated by Django 4.2.11 on 2026-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0072_merge_preseason_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueidentity',
            name='secondary_color',
            field=models.CharField(default='#C41230', help_text='Secondary brand color as a hex code.', max_length=7),
        ),
    ]
