import json
import logging
import time
from pathlib import Path

import requests
from django.conf import settings
from playwright.sync_api import sync_playwright

logger = logging.getLogger(__name__)

DEFAULT_COOKIE_CACHE_PATH = Path(
    getattr(settings, "BLUE_SOMBRERO_COOKIE_CACHE_PATH", "/tmp/bluesombrero_cookies.json")
)
DEFAULT_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 6


class BlueSombreroBrowserLogin:
    """Drives the real Stack Sports login form and interacts with reporting endpoints."""

    def __init__(
        self,
        username=None,
        password=None,
        portal_id="10236",
        app_name="Washington Township Little League",
        instance_key="leagues",
    ):
        self.username = username or getattr(settings, "BLUE_SOMBRERO_USERNAME", None)
        self.password = password or getattr(settings, "BLUE_SOMBRERO_PASSWORD", None)
        self.portal_id = str(portal_id)
        self.app_name = app_name
        self.instance_key = instance_key
        self.stack_client_id = getattr(settings, "BLUE_SOMBRERO_STACK_CLIENT_ID", "612b0399b1854a002e427f78")

        if not self.username or not self.password:
            raise ValueError("BLUE_SOMBRERO_USERNAME and BLUE_SOMBRERO_PASSWORD must be defined.")

    def _login_url(self) -> str:
        redirect_uri = f"https://core-api.bluesombrero.com/login/redirect/portal/{self.portal_id}"
        app_name_encoded = self.app_name.replace(" ", "+")
        return (
            "https://login.stacksports.com/login"
            f"?client_id={self.stack_client_id}"
            f"&redirect_uri={redirect_uri}"
            f"&app_name={app_name_encoded}"
            f"&portalid={self.portal_id}"
            f"&instancekey={self.instance_key}"
        )

    def _perform_login(self, page) -> None:
        """Executes the two-step login on Stack Sports."""
        logger.info("[BROWSER LOGIN] Navigating to Stack Sports login page...")
        page.goto(self._login_url(), wait_until="networkidle", timeout=30000)

        # Step 1: Email
        logger.info("[BROWSER LOGIN] Filling email field...")
        email_input = page.locator("input[name='email']")
        email_input.wait_for(state="visible", timeout=15000)
        email_input.fill(self.username)

        continue_btn = page.locator("button[type='submit'], button:has-text('Continue'), input[type='submit']").first
        continue_btn.click()

        # Step 2: Password
        logger.info("[BROWSER LOGIN] Waiting for password field...")
        password_input = page.locator("input[name='password']")
        password_input.wait_for(state="visible", timeout=15000)
        password_input.fill(self.password)

        submit_btn = page.locator("button[type='submit'], button:has-text('Continue'), button:has-text('Log In'), input[type='submit']").first
        submit_btn.click()

        # Step 3: Wait for auth handoff away from login.stacksports.com
        logger.info("[BROWSER LOGIN] Waiting for redirect away from login domain...")
        page.wait_for_url(lambda url: "login.stacksports.com" not in url, timeout=30000)

    def fetch_report(self, report_id: str) -> dict:
        """
        Logs in via Playwright, navigates to the saved report page,
        and intercepts all report network traffic generated by the page.

        The report UI's own DynamicQuery/execute call uses whatever page
        size the grid component defaults to, which can be smaller than the
        report's total record count. After the natural page load settles,
        _ensure_full_result_set() replays that same call with a forced,
        very large page size so the export never silently truncates.
        """
        captured_responses = []
        captured_requests = {}

        def handle_response(response):
            # Capture JSON responses from the reporting proxy/api endpoints
            if "/proxy/reporting/api/v1/" in response.url and response.status == 200:
                try:
                    data = response.json()
                    captured_responses.append({"url": response.url, "data": data})
                except Exception:
                    pass

        def handle_request(request):
            if "DynamicQuery/execute" in request.url and request.method == "POST":
                # Keep the most recent matching request; the grid may issue
                # more than one as the user's saved view loads.
                captured_requests["execute"] = {
                    "url": request.url,
                    "post_data": request.post_data,
                }

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                )
            )
            page = context.new_page()
            page.on("response", handle_response)
            page.on("request", handle_request)

            try:
                self._perform_login(page)

                reporting_ui_url = f"https://reporting.bluesombrero.com/{self.portal_id}/admin/saved/{report_id}"
                logger.info("[BROWSER LOGIN] Navigating to reporting interface: %s", reporting_ui_url)

                page.goto(reporting_ui_url, wait_until="networkidle", timeout=30000)

                # Wait for the table UI / data elements to load fully in the DOM
                logger.info("[BROWSER LOGIN] Waiting for report table rendering...")
                page.wait_for_timeout(5000)

                self._ensure_full_result_set(page, captured_responses, captured_requests)

                # Return all intercepted endpoint responses so we can inspect all payloads
                return {
                    "report_id": report_id,
                    "portal_id": self.portal_id,
                    "captured_endpoints": captured_responses,
                }

            except Exception:
                logger.exception("[BROWSER LOGIN] Report retrieval failed, current URL: %s", page.url)
                raise
            finally:
                browser.close()

    def _ensure_full_result_set(self, page, captured_responses, captured_requests):
        """
        Checks the DynamicQuery/execute response we already captured against
        its own meta.totalRecords. If the row count came back short, replay
        the exact same request body with a forced large page size and add
        the result to captured_responses, so downstream conversion has a
        complete resultSet to pick up instead of a truncated first page.
        """
        execute_req = captured_requests.get("execute")
        if not execute_req or not execute_req.get("post_data"):
            logger.warning(
                "[BROWSER LOGIN] No DynamicQuery/execute request was captured; "
                "cannot verify or force a full page size."
            )
            return

        last_execute_data = None
        for captured in reversed(captured_responses):
            if "DynamicQuery/execute" in captured.get("url", ""):
                last_execute_data = captured.get("data")
                break

        total_records = None
        row_count = None
        if isinstance(last_execute_data, dict):
            meta = last_execute_data.get("meta") or {}
            total_records = meta.get("totalRecords")
            result_set = last_execute_data.get("resultSet")
            if not isinstance(result_set, dict):
                inner = last_execute_data.get("data")
                if isinstance(inner, dict):
                    result_set = inner.get("resultSet")
            if isinstance(result_set, dict):
                row_count = len(result_set.get("rows", []) or [])

        if total_records is not None and row_count is not None and row_count >= total_records:
            logger.info(
                "[BROWSER LOGIN] Initial execute call already returned all %d records.",
                total_records,
            )
            return

        logger.info(
            "[BROWSER LOGIN] Execute call returned %s of %s records; re-executing with a forced page size.",
            row_count, total_records,
        )

        try:
            body = json.loads(execute_req["post_data"])
        except Exception:
            logger.warning(
                "[BROWSER LOGIN] Could not parse captured execute request body; skipping full-pull retry."
            )
            return

        for size_field in ("pageSize", "take", "limit", "top"):
            if size_field in body:
                body[size_field] = 10000
        body.setdefault("pageSize", 10000)
        if "pageIndex" in body:
            body["pageIndex"] = 0
        if "page" in body:
            body["page"] = 1

        try:
            forced_result = page.evaluate(
                """async ({ url, body }) => {
                    const res = await fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Accept': 'application/json'
                        },
                        body: JSON.stringify(body)
                    });
                    if (!res.ok) throw new Error(`Forced execute failed: ${res.status}`);
                    return await res.json();
                }""",
                {"url": execute_req["url"], "body": body},
            )
        except Exception:
            logger.exception("[BROWSER LOGIN] Forced full-page-size execute call failed.")
            return

        captured_responses.append({"url": execute_req["url"], "data": forced_result})

    def login_and_get_cookies(self) -> dict:
        """
        Drives login flow and extracts browser context cookies.
        """
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                )
            )
            page = context.new_page()

            try:
                self._perform_login(page)
                cookies = context.cookies()
                return {"cookies": cookies}
            finally:
                browser.close()


def fetch_report_with_playwright(report_id: str = "202676", portal_id: str = "10236") -> dict:
    login = BlueSombreroBrowserLogin(portal_id=portal_id)
    return login.fetch_report(report_id=report_id)


def _load_cached_cookies(cache_path: Path, max_age_seconds: int):
    if not cache_path.exists():
        return None
    age_seconds = time.time() - cache_path.stat().st_mtime
    if age_seconds > max_age_seconds:
        return None
    try:
        return json.loads(cache_path.read_text())
    except Exception:
        return None


def _save_cached_cookies(cache_path: Path, auth_data: dict) -> None:
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_text(json.dumps(auth_data))


def get_authenticated_session(
    portal_id="10236",
    report_id="202676",
    app_name="Washington Township Little League",
    instance_key="leagues",
    force_refresh=False,
    cache_path: Path = DEFAULT_COOKIE_CACHE_PATH,
    max_age_seconds: int = DEFAULT_COOKIE_MAX_AGE_SECONDS,
) -> requests.Session:
    """
    Returns a requests.Session pre-populated with cookies obtained via Playwright login.
    """
    cached = None if force_refresh else _load_cached_cookies(cache_path, max_age_seconds)
    if not cached:
        login = BlueSombreroBrowserLogin(portal_id=portal_id, app_name=app_name, instance_key=instance_key)
        cached = login.login_and_get_cookies()
        _save_cached_cookies(cache_path, cached)

    session = requests.Session()
    session.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        )
    })

    cookies = cached.get("cookies", []) if isinstance(cached, dict) else []
    for c in cookies:
        if isinstance(c, dict):
            session.cookies.set(c["name"], c["value"], domain=c.get("domain"), path=c.get("path", "/"))

    return session