# services/payload_config.py

BASE_PAYLOAD = {
    "portalIds": "",
    "columns": [
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.ProgramsProgramName", "caption": "Program Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.DivisionsDivisionName", "caption": "Division Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersFirstName", "caption": "Account First Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersLastName", "caption": "Account Last Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersFirstName", "caption": "Player First Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersLastName", "caption": "Player Last Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersGender", "caption": "Player Gender"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersDateOfBirth", "caption": "Player Birth Date"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersStreet", "caption": "Street Address"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersUnit", "caption": "Unit"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersCity", "caption": "City"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersRegion", "caption": "State"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersPostalCode", "caption": "Postal Code"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersEmail", "caption": "User Email"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersTelephone", "caption": "Telephone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersCellPhone", "caption": "Cellphone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersOtherPhone", "caption": "Other Phone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsTeamName", "caption": "Team Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersOrderDate", "caption": "Order Date"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersOrderId", "caption": "Order No"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsDetail", "caption": "Order Detail Description"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsOrderItemAmount", "caption": "OrderItem Amount"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsPaymentItemAmount", "caption": "OrderItem Amount Paid"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsBalanceItemAmount", "caption": "OrderItem Balance"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersPaymentStatus", "caption": "Order Payment Status"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoTshirtSizeIdTshirtSizeSizeDescription", "caption": "Jersey Size"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoAllergies", "caption": "Player Allergies"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoEmergencyContFirstName", "caption": "Player Emergency Contact First Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoEmergencyContLastName", "caption": "Player Emergency Contact Last Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoEmergencyTel", "caption": "Player Emergency Telephone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoInsuranceCompany", "caption": "Player Insurance Company"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoInsurancePolicyHolder", "caption": "Player Insurance Policy Holder"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoInsurancePolicyNumber", "caption": "Player Insurance Policy Number"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoPhysicalConditions", "caption": "Player Physical Conditions"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoWaiver", "caption": "Player Waiver"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoPlayerVerificationWaiver", "caption": "Player Verification Waiver"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoShortSizeIdTshirtSizeSizeDescription", "caption": "Shorts Size"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoSocksSizeIdTshirtSizeSizeDescription", "caption": "Socks Size"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoPantsSizeIdTshirtSizeSizeDescription", "caption": "Pants Size"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoSpecialPlayerRequest", "caption": "Special Player Request"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoTetanusShot", "caption": "Tetanus Shot"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoTetanusDate", "caption": "Tetanus Shot Date"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoPositionPlayed", "caption": "Position Played"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.RaceEstimatedFinishTime", "caption": "Race Estimated Finish Time"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.RaceShirt", "caption": "Race Shirt"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoIsNewCustomer", "caption": "New Or Returning"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoSchoolName", "caption": "School Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoLittleLeagueSchoolName", "caption": "Little League School Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoCurrentGrade", "caption": "Current Grade"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoRisingGrade", "caption": "Rising Grade"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoTeammateRequest", "caption": "Teammate Request"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoCoachRequest", "caption": "Coach Request"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoPreviousCoach", "caption": "Previous Coach"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoExperienceInYear", "caption": "Years of Experience"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AdditionalPlayerInfoUslmemberNumber", "caption": "USL Membership Number"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.LittleLeagueEligibility", "caption": "Little League Eligibility"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AssociationPlayerId", "caption": "Association Player ID"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsProgramName", "caption": "Order Detail Program Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsDivisionName", "caption": "Order Detail Division Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsDepositOnly", "caption": "Order Deposit Only"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsOrderDepositOnlyAmount", "caption": "Order Deposit Only Amount"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderDetailsPlayerId", "caption": "Order Detail Player Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersOrderAmount", "caption": "Order Amount"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersTimeStamp", "caption": "Order Time Stamp"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersBillToFirstName", "caption": "Billing First Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersBillToLastName", "caption": "Billing Last Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersBillToAddress1", "caption": "Billing Address"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersCreditCardNumber", "caption": "Last 4 of CC"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersCardExpireMonth", "caption": "Order Card Expiry Month"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersCardExpireYear", "caption": "Order Card Expiry Year"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersOrderNotes", "caption": "Orders Order Notes"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersStatus", "caption": "Order Status"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersPaymentMessage", "caption": "Order Payment Message"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersPaymentAmount", "caption": "Order Payment Amount"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersTotalCcfee", "caption": "User Paid CC Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersTotalRegFee", "caption": "User Paid Registration Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersAdminCcfee", "caption": "Admin Paid CC Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersAdminRegFee", "caption": "Admin Paid Registration Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersTotalPaymentAmount", "caption": "Total Payment Amount"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrdersPaymentMethod", "caption": "Order Payment Method"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.NonVolunteerFee", "caption": "Non-Volunteer Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderNotesOrderId", "caption": "Order Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OrderNotes", "caption": "Order Notes"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdporderDetailPaymentId", "caption": "ODP Order Detail Payment Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdporderDetailId", "caption": "ODP Order Detail Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdporderPaymentHistoryId", "caption": "ODP Payment History Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdppaidAmount", "caption": "ODP Paid Amount"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdppaidRegFee", "caption": "ODP Paid Reg Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdppaidCcfee", "caption": "ODP Paid CC Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdpcreatedBy", "caption": "ODP Created By"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OdpcreatedDate", "caption": "ODP Created Date"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphorderId", "caption": "OPH Order Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphpaymentDate", "caption": "OPH Payment Date"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphbillToFirstName", "caption": "OPH Bill To First Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphbillToLastName", "caption": "OPH Bill To Last Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphbillToAddress", "caption": "OPH Bill To Address"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphbillToCity", "caption": "OPH Bill To City"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphbillToState", "caption": "OPH Bill To State"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphbillToZip", "caption": "OPH Bill To Zip"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphpaymentAmount", "caption": "OPH Payment Amount"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphpaymentMethod", "caption": "OPH Payment Method"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphorderNotes", "caption": "OPH Order Notes"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphcreditCardNumber", "caption": "OPH Credit Card Number"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphcardExpireMonth", "caption": "OPH Card Expiry Month"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphcardExpireYear", "caption": "OPH Card Expiry Year"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphtransactionId", "caption": "OPH Transaction Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphauthCode", "caption": "OPH Auth Code"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphavsCode", "caption": "OPH Avs Code"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphpaymentStatus", "caption": "OPH Payment Status"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphisOpenOrderPayment", "caption": "OPH Is Open Order Payment"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphorderPaymentHistoryId", "caption": "OPH Order Payment History Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OpholdOrderPaymentHistoryId", "caption": "OPH Old Order Payment History Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphcreditCardType", "caption": "OPH Credit Card Type"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.Ophccfee", "caption": "OPH CC Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.OphperRegFee", "caption": "OPH Per Reg Fee"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersPlayerId", "caption": "Player Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersMiddleInitial", "caption": "Player Middle Initial"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.DateOfBirth", "caption": "Birth Date Time Stamp"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersAge", "caption": "Player Age"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.LittleLeagueAgeBaseball", "caption": "Little League Age (Baseball)"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.LittleLeagueAgeSoftball", "caption": "Little League Age (Softball)"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersEmail", "caption": "Player Email"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersStreet", "caption": "Player Street"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersUnit", "caption": "Player Unit"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersCity", "caption": "Player City"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersRegion", "caption": "Player State"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersPostalCode", "caption": "Player Postal Code"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersTelephone", "caption": "Player Telephone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersRegionCode", "caption": "Player State Abbreviation"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersCellphone", "caption": "Player Cellphone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersRegistrationNumber", "caption": "Registration Number"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersJerseyNumber", "caption": "Player Jersey Number"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayerEvaluationComment", "caption": "Player Evaluation Comment"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayerEvaluationRating", "caption": "Player Evaluation Rating"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayerEvaluationRanking", "caption": "Numeric Ranking (Auto Assign)"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayerVerificationComment", "caption": "Birth Certificate Note"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayersRecentTeam", "caption": "Recent Team"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TryoutRejectionEmailSent", "caption": "Tryout Rejection Email Sent"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AcceptedTryout", "caption": "Tryout Acceptance Status"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TryoutAcceptanceEmailStatus", "caption": "Tryout Acceptance Email Status"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.NewRegistrant", "caption": "New Registrant"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayDown", "caption": "Play Down"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.BirthCertificate", "caption": "Birth Certificate"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.VerificationNote", "caption": "Verification Note"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayerSuffix", "caption": "Player Suffix"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PlayerWeight", "caption": "Weight"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.AssociatedTeamStaff", "caption": "Associated Team Staff"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.PortalsPortalName", "caption": "Portal Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.ProgramsProgramId", "caption": "Program Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.ActivityType", "caption": "Activity Type"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.ProgramsProgramTypeIdProgramTypesProgramTypeName", "caption": "Program Type"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.ProgramTypeLevel", "caption": "Level"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.SportsAffiliationName", "caption": "National Affiliation Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsTeamId", "caption": "Team Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsJerseyColor", "caption": "Jersey Color"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStateTeamNumber", "caption": "State Team Number"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStateAgeGroupName", "caption": "State Age Group Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStateLevelName", "caption": "State Level Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStateClubName", "caption": "State Club Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStateLeagueName", "caption": "State League Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStateDistrictName", "caption": "State District Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStateAssociationName", "caption": "State Association Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.TeamsStatePlayingAssociationName", "caption": "State Playing Association Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersUserId", "caption": "User Id"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersParentName", "caption": "Parent Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersMiddleInitial", "caption": "Account Middle Initial"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersGender", "caption": "Gender"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecEmailId", "caption": "Additional Email"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSuffix", "caption": "Suffix"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersAccountCreatedDate", "caption": "Account Created Date"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecFirstName", "caption": "Additional First Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecMiddleInitial", "caption": "Additional Middle Initial"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecLastName", "caption": "Additional Last Name"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecSuffix", "caption": "Additional Suffix"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecStreet", "caption": "Additional Street"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecUnit", "caption": "Additional Unit"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecCity", "caption": "Additional City"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecRegion", "caption": "Additional State"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecPostalCode", "caption": "Additional Postal Code"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecTelephone", "caption": "Additional Telephone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecCellPhone", "caption": "Additional Cellphone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersSecOtherPhone", "caption": "Additional Other Phone"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersAdditionalEmailId", "caption": "Secondary Email"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersRelationship", "caption": "Relationship to Participant"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.HeardFrom", "caption": "Heard From"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UsersAdminNotes", "caption": "Admin Account Notes"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.UserRole", "caption": "User Role"},
        {"id": "ReportWizardEnrollmentDetailsNewRegistration.Contact", "caption": "Contact"}
    ],
    "conditions": [
        {"id": "DivisionsEndDate", "operator": "IsAfterSpecial", "value": "Today", "dataType": "Date", "value2": None},
        {"id": "OrdersPaymentStatus", "operator": "NotEqual", "value": "Cancelled", "dataType": "String", "value2": None},
        {"id": "OrdersPaymentStatus", "operator": "NotEqual", "value": "Failed", "dataType": "String", "value2": None}
    ],
    "modelId": "ReportWizard_EnrollmentDetails_New_Registration",
    "reportKey": "ReportWizardEnrollmentDetailsNewRegistration",
    "customQuestionIds": "22504865,22504870,22504868,22504871,22504872,22504873,22504874,22504875,22504876,22504880,22504892,22504893,22504268,22504269,22504270,22504272,22504262,22504263,22504264,22504265,22504266,22504267,22504271,22504273,22504274",
    "feeDiscountQuestionIds": "1107948,1107930",
    "page": 1,
    "pageSize": 100,
    "needTotal": True,
    "sort": {
        "id": "ReportWizardEnrollmentDetailsNewRegistration.ProgramsProgramName",
        "direction": "asc"
    }
}